### PR TITLE
add the following changes :-

### PR DESCRIPTION
**Pull request by imaaquibali**
-  add the hover effect on order summery &  checkout section.
- remove unwanted text below checkout button.
- change the color after hover on order summery section.
- make it look better than before 

## if you like these changes please merge it with hacktoberfest-accepted label

### CODE REVIEW

**Comment by AaquibAli** [comment]
- made it responsive for  phones

**Comment by ieiciet** [comment]
Resolved Conflicts. Take care in future before creating a PR.
Visit your commits again as they are making the page look a bit ugly. Good work tho'

**Comment by imaaquibali** [comment]
okk

**Comment by imaaquibali** [comment]
@ieiciet  can u tell me which changes i have to do ??? so u merge it

**Pull request closed without merging**
